import React from 'react'
export {default as Footer } from './footer/Footer'
export {default as Landingpage } from './landingpage/Landingpage'
export {default as Service} from './service/Service'
export {default as About} from './about/About'
export {default as User} from './user/User'
export {default as EditProfile} from './edit-profile/EditProfile'
export {default as Jobpost} from './job-post/Jobpost'
export {default as Jobs} from './jobs/Jobs'
export {default as Chat} from './chat/chat'
export {default as Repairer} from './repairer/Repairer'
export {default as jobPage} from './job-page/jobPage'
export {default as Help} from './help/Help'

