import React from 'react'

export {default as Navbar} from './navbar/Navbar'
export {default as Separator} from './separator1/Separator'
export {default as About2} from './about2/About2'
export {default as Process} from './process/Process'
export {default as Form} from './form/Form'
export {default as Login} from './login/Login'
export {default as Lastfooter} from './last-footer/Lastfooter'
export {default as Navbar2} from './navbar2/Navbar2'
export {default as Navbar3} from './navbar3/Navbar3'